### ISSUE TITLE
Support for command-line based template definitions?

### ISSUE THREAD

**Issue by jpap** [jimmyfrasche/autoreadme#9]
Thanks for a great project!

I am currently creating a per-package Markdown template so that I can set the top-level title to a human-readable string that is more descriptive than the package name alone.

It would be great if we could define template strings on the command line, so that the template file can remain generic.

For example,
```
autoreadme -def 'title=My Great Package' -f -template .README.template.md
```
would allow us to use the value `{{.title}}` (and/or `{{.Title}}`?) in the `.README.template.md` file, and would evaluate to "My Great Package".

The proposed `-def` flag would be able able to be supplied multiple times for different template strings.

**Comment by jimmyfrasche** [comment]
I'm not sure about this change. I see the issue but I'm not certain this solution is the best way to go about it.

The goal of this command is to not worry about the README so having to pass command line arguments for every refresh takes away from that. Arguably that's also true of having to pass a path to a template or to maintain multiple identical copies of a single template

It seems like a better solution, in general and in this case, would be to allow a master template per project. I think that may have to wait for #7 and in the meantime you may just have to have a fork.

**Comment by jpap** [comment]
Thanks for considering this change and for your note.  I [ended up forking the project](https://github.com/jpap/godoc-readme-gen) because there was a bunch of other changes I wanted, and I wasn't sure how "alive" this project was because the last commit was several years prior.

I found that having a way to control the README title/heading was very helpful, without having to add a per-project template, where the command line "configuration" is located in the same file as the project godoc as a `//go:generate` directive.  I typically place package doc comments in a dedicated `00doc.go` file, and I place the `//go:generate` directive underneath the `package` declaration in the same file.

**Comment by jimmyfrasche** [comment]
No problem. Thanks for the update from the code copied in from go/doc—I had missed that. I wish I could say this project were more alive but I really haven't gotten around to redesigning it for modules yet and there. Good luck with the fork!

**Comment by jpap** [comment]
Thank you.  The fork has already been updated to use `x/tools/go/packages` and works well with Go modules.  Appreciate any feedback you might have if you ever get a chance to look at it.

**Comment by jimmyfrasche** [comment]
FYI: I pushed a new branch (shortly to become the default branch) that has a compromise: each directory may contain a README.md.data file that is parsed as JSON and accessible in the template. That allows adding arbitrary structured data that's part of the repo so there's no need for shell scripts or having to manually specify flags each time. It also changes a bunch of other stuff so be sure to read the docs, caveat user, etc.
